//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string ItemFile {
            get {
                return ResourceManager.GetString("ItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Exit 的本地化字符串。
        /// </summary>
        public static string ItemFileExit {
            get {
                return ResourceManager.GetString("ItemFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _New 的本地化字符串。
        /// </summary>
        public static string ItemFileNew {
            get {
                return ResourceManager.GetString("ItemFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open 的本地化字符串。
        /// </summary>
        public static string ItemFileOpen {
            get {
                return ResourceManager.GetString("ItemFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save 的本地化字符串。
        /// </summary>
        public static string ItemFileSave {
            get {
                return ResourceManager.GetString("ItemFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string ItemHelp {
            get {
                return ResourceManager.GetString("ItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _About 的本地化字符串。
        /// </summary>
        public static string ItemHelpAbout {
            get {
                return ResourceManager.GetString("ItemHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue cube 的本地化字符串。
        /// </summary>
        public static string ToolCubeBlue {
            get {
                return ResourceManager.GetString("ToolCubeBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green cube 的本地化字符串。
        /// </summary>
        public static string ToolCubeGreen {
            get {
                return ResourceManager.GetString("ToolCubeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red cube 的本地化字符串。
        /// </summary>
        public static string ToolCubeRed {
            get {
                return ResourceManager.GetString("ToolCubeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White cube 的本地化字符串。
        /// </summary>
        public static string ToolCubeWhite {
            get {
                return ResourceManager.GetString("ToolCubeWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cursor 的本地化字符串。
        /// </summary>
        public static string ToolCursor {
            get {
                return ResourceManager.GetString("ToolCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination 的本地化字符串。
        /// </summary>
        public static string ToolDestination {
            get {
                return ResourceManager.GetString("ToolDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eraser 的本地化字符串。
        /// </summary>
        public static string ToolEraser {
            get {
                return ResourceManager.GetString("ToolEraser", resourceCulture);
            }
        }
    }
}
