[package]
edition = "2021"
name = "cube-collection"
version = "0.5.15"

[dependencies]
# Local workspace
cube-core = { path = "../cube-core" }

# Bevy and its plugins
bevy = "0.18.0"
bevy_prototype_lyon = "0.16"

# Extra utilities
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
snafu = "0.8"
toml = "1.0"
